[tool.ruff]
line-length = 119
lint.extend-select = ["I"]

[project]
name = "gym-lowcostrobot"
description = "Robotics environments for the Gymnasium repo."
readme = "README.md"
dynamic = ["version"]

[project.entry-points."gymnasium.envs"]
__root__ = "gym_lowcostrobot.__init__:register_robotics_envs"